### ISSUE TITLE
NumberFormatException for input string ""

### ISSUE THREAD

**Issue by MaxEtMoritz** [zacharee/SamloaderKotlin#27]
I tried to download the Stock Firmware for my Device today, SM-G900F and Region BTU. Checking for Updates worked without problem, but clicking "Download" led to an Error. Stack Trace:
```
java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.base/java.lang.Long.parseLong(Unknown Source)
        at java.base/java.lang.Long.parseLong(Unknown Source)
        at tk.zwander.common.tools.Request.getBinaryFile(Request.kt:179)
        at tk.zwander.common.tools.Request$getBinaryFile$1.invokeSuspend(Request.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
I Itried it on Windows 10 if that's important.
Edit: Tried to download the Firmware with samloader, similar issue there. Maybe there is something messed up at Samsung's side?

**Comment by zacharee** [comment]
Looking at the response generated by Samsung, there's no file size reported, no file path reported, and a whole bunch of other missing information. The DBT CSC seems to have a proper file, but the current version will crash if you try to check with it. I'm working on fixing that.
