### ISSUE TITLE
Unable to download Firmware on windows

### ISSUE THREAD

**Issue by DarkKnight1995** [zacharee/SamloaderKotlin#91]
Hello mate, I have been trying to download the latest firmware for galaxy feel 2 (Model: **SC-02L**, CSC: **DCM**) since yesterday on Windows 10 22H2 (19045.2604). I have tried using v1.13.0 and v1.14.0 but it gives the following exception on the console;

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Generating nonce.
Nonce: j0keio2xhdynz8m4
Auth: n0bMi6412bVpqT5UDrLO6wMiRJ0+kybXE7sbTJX/8Bo=
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 8
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at tk.zwander.common.tools.Request.getBinaryFile(Request.kt:279)
        at tk.zwander.common.tools.Request$getBinaryFile$1.invokeSuspend(Request.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

Also attached are some screenshots from the tool (16 pics in zip file).
[Bifrost-ScreenShots.zip](https://github.com/zacharee/SamloaderKotlin/files/10774030/Bifrost-ScreenShots.zip)

I have tried turning off the AV on my pc and also ran the program as admin but it still gives the error. There is also no space in the directory name (D:\Bifrost\Bifrost.exe). Please help.

**Comment by zacharee** [comment]
This should be fixed in https://github.com/zacharee/SamloaderKotlin/releases/tag/1.14.1.
